# v2026-02-efficient-r1 - Evans AI Core
__version__ = "1.0.0"

from .memory import (
    MemorySystem,
    remember,
    recall,
    search_memories,
    learn_from_interaction,
    get_user_preferences,
    learn_skill,
    get_learned_skills,
)
from .mcp import MCPServer, MCPClient, MCPMgr, create_server, create_client
from .tools import ToolRegistry, bash, read_file, write_file, exec_tool
from .skills import Skill, SkillRegistry, skill, get_skill, list_skills
from .server import (
    HTTPServer,
    WebSocketServer,
    TCPServer,
    WebSocketClient,
    TCPClient,
    create_api_server,
    create_ws_server,
    create_tcp_server,
)
from .prompts import (
    PromptInjector,
    PromptManager,
    prompt_manager,
    inject_system,
    build_prompt,
    add_context,
    get_context,
)
from .proactive import (
    ProactiveEngine,
    proactive_engine,
    trigger_action,
    analyze_and_act,
    learn_user_behavior,
    set_user_context,
)

__all__ = [
    "MemorySystem",
    "remember",
    "recall",
    "search_memories",
    "learn_from_interaction",
    "get_user_preferences",
    "learn_skill",
    "get_learned_skills",
    "MCPServer",
    "MCPClient",
    "MCPMgr",
    "create_server",
    "create_client",
    "ToolRegistry",
    "bash",
    "read_file",
    "write_file",
    "exec_tool",
    "Skill",
    "SkillRegistry",
    "skill",
    "get_skill",
    "list_skills",
    "HTTPServer",
    "WebSocketServer",
    "TCPServer",
    "WebSocketClient",
    "TCPClient",
    "create_api_server",
    "create_ws_server",
    "create_tcp_server",
    "PromptInjector",
    "PromptManager",
    "prompt_manager",
    "inject_system",
    "build_prompt",
    "add_context",
    "get_context",
    "ProactiveEngine",
    "proactive_engine",
    "trigger_action",
    "analyze_and_act",
    "learn_user_behavior",
    "set_user_context",
]
